<?php

use Drupal\novel\TwigCsFixer\Rules\RequireDesignSystemLibraryRule;
use TwigCsFixer\Config\Config;
use TwigCsFixer\File\Finder;
use TwigCsFixer\Ruleset\Ruleset;
use TwigCsFixer\Standard\TwigCsFixer;

$themePath = __DIR__ . '/web/themes/custom/novel/assets/dpl-design-system';

$ruleset = new Ruleset();
$ruleset->addStandard(new TwigCsFixer());
$ruleset->addRule(new RequireDesignSystemLibraryRule(
    componentCssDir: $themePath . '/css/components',
    ignorePatterns: [
        // skeleton-screen-css (nullilac/skeleton-screen-css) —
        // provides loading placeholder elements and layout utilities.
        '/^ssc/',             // skeleton elements (.ssc-line, .ssc-circle etc.)
        '/^w-\d+$/',          // width helpers (w-10 through w-100)
        '/^(inline-)?flex/',  // flexbox layout helpers
        '/^justify-/',        // justify-content helpers

        // Swiper — third-party carousel library.
        '/^swiper/',

        // Drupal form system — class names generated by Drupal's
        // form API that must match the rendered HTML.
        '/^js-form-/',
        '/^form-(item|type|wrapper|composite|checkboxes)/',


    ],
));

return (new Config())
  ->allowNonFixableRules()
  ->setRuleset($ruleset)
  ->setFinder((new Finder())
    ->path('web/themes/custom/')
    ->path('web/modules/custom/')
  );
