<?php

use Drupal\novel\TwigCsFixerRules\RequireDesignSystemLibraryRule;
use TwigCsFixer\Config\Config;
use TwigCsFixer\File\Finder;
use TwigCsFixer\Ruleset\Ruleset;
use TwigCsFixer\Standard\TwigCsFixer;

$ruleset = new Ruleset();
$ruleset->addStandard(new TwigCsFixer());
$ruleset->addRule(new RequireDesignSystemLibraryRule(
    ignorePatterns: [
        // skeleton-screen-css (nullilac/skeleton-screen-css) —
        // provides loading placeholder elements and layout utilities.
        '/^ssc/',
        '/^w-\d+$/',
        '/^(inline-)?flex/',
        '/^justify-/',

        // Swiper — third-party carousel library.
        '/^swiper/',

        // Drupal form system — class names generated by Drupal's
        // form API that must match the rendered HTML.
        '/^js-form-/',
        '/^form-(item|type|wrapper|composite|checkboxes)/',
    ],
    libraryPrefix: 'novel/',
));

return (new Config())
  ->allowNonFixableRules()
  ->setRuleset($ruleset)
  ->setFinder((new Finder())
    ->path('web/themes/custom/')
    ->path('web/modules/custom/')
    ->exclude('tests')
  );
