---
name: Design / Tag-release workflow

on:
  workflow_call:

jobs:
  create_release:
    name: Design / Create release on tagging
    uses: ./.github/workflows/common-release-workflow.yml
    with:
      project: 'design-system'
      sha: ${{ github.sha }}
      branch: ${{ github.ref_name }}
      dev_release: false

  create_npm_package:
    name: Design / Create and Release NPM package on tagging
    uses: ./.github/workflows/design-system-npm-workflow.yml
    needs: create_release
    permissions:
      contents: read
      packages: write
    with:
      tag_name: ${{ github.ref_name }}
      npm_version: ${{ github.ref_name }}
      latest: true
